# Site settings
title: I Do Technology
email: info@ido.technology
description: > # this means to ignore newlines until "baseurl:"
  This static website generator... jekyll is confugling.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://test.ido.technology" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
